import json,pathlib
p=pathlib.Path(__file__).parent
sources={
'W26':{'title':'Walmart FY2026 ESG Report','url':'https://corporate.walmart.com/content/dam/corporate/documents/esgreport/2026/FY2026-Walmart-ESG-Report.pdf','locator':'printed p.31; visually verified saved page','excerpt':'Our capital plan includes funding for these replacements','type':'company disclosure'},
'W25':{'title':'Walmart FY2025 ESG Report','url':'https://corporate.walmart.com/content/dam/corporate/documents/esgreport/2025/FY2025-Walmart-ESG-Report.pdf','locator':'Onsite Refrigerants / Investing in Lower-GWP Systems','excerpt':'408 U.S. facilities','type':'company disclosure'},
'CDP24':{'title':'Walmart 2024 CDP response','url':'https://corporate.walmart.com/content/dam/corporate/documents/esgreport/2025/2024-Walmart-CDP-Response.pdf?cid=esgreport','locator':'printed pp.151,154–155,207–208; questions 7.10.1,7.15.1,7.55.2','excerpt':'primarily due to increased leaks from systems with R-404A refrigerant','type':'company disclosure; CY2023 inventory'},
'DOE15':{'title':'DOE/Navigant Hannaford transcritical CO2 case study, January 2015','url':'https://www.energy.gov/sites/prod/files/2015/02/f19/Hannaford%20Study%20Report%201-22-2015_CLEAN.pdf','locator':'printed pp.1–3,6,18–24; Table V.2 p.20','excerpt':'Site (MMBtu)','type':'external paired-store field study'},
'ORNL18':{'title':'Integrated supermarket refrigeration for very high ambient temperature','url':'https://www.ornl.gov/publication/integrated-supermarket-refrigeration-very-high-ambient-temperature','locator':'abstract; Energy 165A pp.572–590, September 2018','excerpt':'analytically investigates','type':'analytical research; not Walmart field measurement'},
'EPA11':{'title':'EPA GreenChill Commercial Refrigeration Leak Prevention and Repair, May 2011','url':'https://www.epa.gov/sites/production/files/documents/leakpreventionrepairguidelines.pdf','locator':'printed p.2; refrigerant table and supermarket leakage discussion','excerpt':'rates less than 5% are achievable','type':'historical industry guidance'},
'EPA24':{'title':'EPA GHG Emission Factors Hub, June 2024','url':'https://www.epa.gov/system/files/documents/2024-02/ghg-emission-factors-hub-2024.pdf','locator':'p.1, Table 1, Propane Gas and Propane rows','excerpt':'combustion emissions only','type':'physical inventory factors; audit cross-check'},
'EPA_CERT':{'title':'EPA GreenChill store certification criteria','url':'https://www.epa.gov/greenchill/about-store-certification','locator':'New Eligibility Criteria in 2025; Category 2','excerpt':'GWP-weighted','type':'current voluntary program criteria'}
}
e=[]
def rec(claim,value,unit,period,source,locator,typ,**kw):e.append(dict(claim=claim,value=value,unit=unit,period=period,source=sources[source]['url'],sourceId=source,locator=locator,type=typ,**kw))
rec('Global onsite refrigerant emissions',4080000,'tCO2e/year','FY2026','W26','p.31 emissions table','company reported inventory')
rec('Onsite refrigerant emissions change',-20.7,'percent year over year','FY2026','W26','p.31','achieved inventory change; not intervention causal estimate')
rec('U.S. facilities partly or fully using ultra-low-GWP systems',619,'facilities','2025-12-31','W26','p.31 Using Lower-GWP Refrigeration Systems','installed deployment',limitation='Not full conversions; includes varied facility types, HVAC and multiple fluids. No emissions/capacity denominator.')
rec('Earlier U.S. facilities partly or fully using ultra-low-GWP systems',408,'facilities','2024','W25','Onsite Refrigerants section','installed deployment')
rec('Change in reported partial/full facility count',211,'facilities','2024 to 2025','W26','619 minus W25 408','calculated disclosure-count difference',limitation='Not a verified count of 211 completed full-store conversions.')
rec('Some replacement projects reduce installed legacy refrigerant footprint',80,'percent, approximately','FY2026 disclosure','W26','p.31','company claim; stock footprint',limitation='Source does not define mass versus GWP-weighted stock precisely. Not annual leakage or whole-store reduction; no representative site average.')
rec('New Walmart stores and Sams Clubs install transcritical CO2 refrigeration',100,'percent system designation in new installations','FY2026 disclosure','W26','p.31','existing company policy',limitation='No future new-build emissions credit additional to this policy; not global installed-share statistic.')
rec('In-house refrigeration/HVAC technician workforce',600,'technicians, more than','FY2026','W26','p.31','operational capacity disclosure')
rec('Historical HFC Scope 1 emissions',4432447,'tCO2e','CY2023 in CDP2024','CDP24','p.154 question7.15.1 row4','historical gas-family inventory',limitation='Not current onsite-only refrigerant inventory or gas blend shares; includes broader Scope1 boundary.')
rec('Historical HCFC Scope 1 emissions',106468,'tCO2e','CY2023 in CDP2024','CDP24','p.155 question7.15.1 row6','historical gas-family inventory')
rec('Historical R-404A relevance','Major driver of increased refrigerant leaks','qualitative','CY2023 vs CY2022','CDP24','p.151 question7.10.1','company attribution',limitation='Establishes R-404A use, not its current share.')
for claim,vals,unit in [('Whole-store electricity',[1414683,1415920],'kWh'),('Whole-store propane',[766,1543],'MMBtu'),('Reported propane emissions',[13.18,26.56],'tCO2e'),('Direct refrigerant impact',[191,0.1],'tCO2e'),('Reported net impact',[1179,1003],'tCO2e')]:rec(claim,vals,unit,'Table V.2 September 2013–July 2014','DOE15','p.20 Table V.2; Bradford then Turner','external study reported',limitation='Not annualized. Refrigerant paragraph describes year-long leak data while table is labelled September–July.')
rec('Measured leaked refrigerant mass, each store',200,'lb','Study described year-long leakage','DOE15','p.19 and p.20','external measurement')
rec('Direct reduction computed from rounded study values',100*(1-.1/191),'percent','study comparison','DOE15','Table V.2','calculated external sensitivity; not Walmart factor')
rec('Refrigeration equipment incremental cost',40,'percent approximate premium','2013 installation; report2015','DOE15','p.6','historical external case cost',limitation='Not current Walmart capex; separate from piping/cases cost denominator.')
rec('Piping and display case incremental cost',[10,15],'percent premium','2013 installation; report2015','DOE15','p.6','historical external case cost')
rec('Propane gas combustion CO2 factor',61.46,'kgCO2/MMBtu','EPA2024 factors','EPA24','p.1 Table1 Propane Gas','inventory conversion factor')
rec('Liquid propane combustion CO2 factor',62.87,'kgCO2/MMBtu','EPA2024 factors','EPA24','p.1 Table1 Petroleum Products Propane','inventory conversion factor')
rec('Stores can sustain annual leak rates below',5,'percent charge/year','historical EPA2011','EPA11','p.2','external achieved feasibility; not Walmart baseline')
rec('R-404A direct warming factor',3922,'kgCO2e/kg emitted','EPA2011 table; source GWP convention','EPA11','p.2 Table1','physical factor; align GWP vintage before inventory comparison')
rec('Highest modeled efficiency advantage NH3/CO2 versus all-CO2',12.23,'percent','2018 modeled extreme warm climates','ORNL18','abstract','external model',limitation='Comparison of two natural refrigerant architectures, not against Walmart baseline.')
rec('Highest modeled total emissions advantage NH3/CO2 versus all-CO2',11.20,'percent','2018 modeled extreme warm climates','ORNL18','abstract','external model')
rec('Primary refrigerant GWP criterion for new certification category',150,'GWP upper threshold, strict less than','2025 onward EPA program','EPA_CERT','Category2','voluntary criterion; not statutory conversion requirement')
audit=[]
for ef in [61.46,62.87]:
 b=975+191+766*ef/1000;t=976+.1+1543*ef/1000
 audit.append(dict(propaneFactorKgCO2PerMMBtu=ef,bradfordReconstructed=b,turnerReconstructed=t,differenceTCO2e=b-t,reductionFraction=(b-t)/b,basis='Retains source rounded electricity/refrigerant impacts; recomputes propane CO2 only using printed MMBtu. Excludes methane/N2O and upstream impacts. Diagnostic sensitivity, not corrected validated result.'))
unknown=['FY2026 refrigerant blend and emitted-mass breakdown by site','Onsite inventory split between food refrigeration and HVAC','Walmart absolute leak rate and charge by system','Global and U.S. emissions-weighted conversion eligibility by 2031','Full versus partial coverage inside the 619 facilities','Specific asset retirement and committed conversion schedule','Current replacement bids, project payback and marginal funding need','Matched energy/heat-recovery performance by climate, load and grid','Unresolved DOE propane input unit/conversion discrepancy and mixed period descriptions']
invest={'status':'Mechanisms identified; investable volume and repayable economics unproven','alreadyCommitted':'Walmart capital plan funds replacements as refrigeration/HVAC equipment reaches end of life; new-store CO2 adoption already policy.','historicalCostEvidence':'Hannaford2013 equipment premium~40%; piping/cases premium10–15% on separate components. Maintenance on par with chain average; special pilot monitoring additional. No reliable present Walmart payback.','cashRepayment':'Potential verified avoided refrigerant purchases, repairs, energy and spoilage costs; site energy can increase. Social damage valuation is not cash available for repayment.','incrementalFundEffect':None,'additionalityTest':'Compare funding intervention to asset-specific already-funded replacement date and existing maintenance/regulatory baseline; credit only earlier verified reductions until counterfactual catches up.','feasibleProjectTypes':['Leak repair and monitoring with measured refrigerant purchase savings','Equipment replacement only after cooling-service, lifetime energy, cost and schedule diligence','Technician/vendor capacity contracts only where bottleneck and extra completed assets can be demonstrated'],'requiredData':unknown[:8]}
updates={'status':'Conditional direct-emissions sensitivity; net gap unknown','summary':'Walmart reports 4.08 million tonnes from onsite refrigerants and a 20.7% year-over-year decline. Low-impact systems are already deployed, but public disclosures do not quantify the remaining emissions-weighted conversion opportunity.','boundary':'Global onsite refrigerant leakage including refrigeration/HVAC; excludes energy and lifecycle effects','opportunity':'Test additional leak prevention and accelerated asset replacements against Walmart’s funded replacement schedule.','constraints':['25/50/100% coverage remains an assumption; no measured eligible share or funding effect.','619 U.S. facilities use ultra-low-GWP systems partly or fully; this cannot be divided into global emissions or treated as completed full conversions.','Some projects report about80% reduction in installed legacy refrigerant footprint; this is not annual leakage savings.','The external191 vs0.1 comparison supports only an equal-leaked-mass direct sensitivity, not a Walmart net reduction.','The DOE study reports about15% lower whole-store impact, but a propane unit/conversion discrepancy prevents validating that net figure.','Already funded replacements and new-store CO2 policy form part of the counterfactual.'],'steps':['Baseline is4.08 million tCO2e of FY2026 onsite refrigerant emissions.','The99.95% direct factor comes from rounded numbers in an external paired-store study, at equal leaked mass.','Multiply only by explicitly assumed emissions coverage; eligibility, energy changes and additional fund effect remain unmeasured.','Keep historical achieved reductions and existing commitments separate from prospective additional savings.']}
d={'company':'Walmart','asOf':'2026-09-12','completionStatus':'complete; no app file edited','suggestedUpdates':updates,'recommendation':'Retain old arithmetic only as an explicitly illustrative sensitivity; do not elevate to measured preventable damage or use 80%/619 as replacement eligibility. Prefer unknown company net gap plus measured baseline and site-level physical calculator.','baselineNeedsCorrection':False,'reductionFactorNeedsQualification':True,'measuredEligibleShare':None,'measuredNetPreventableTCO2e':None,'additionalFundTCO2e':None,'evidenceRecords':e,'investmentEvidence':invest,'additionalMetrics':[{'label':'Verified avoided R-404A leak, per kilogram/year','value':3.922,'unit':'tCO2e/year','type':'unit-process calculation','formula':'1kg/year ×3922kgCO2e/kg /1000','limitation':'Only for verifiedR-404A avoided mass; not current Walmart opportunity; no energy credit.'},{'label':'Newly reported partial/full low-GWP facilities','value':211,'unit':'facilities','type':'disclosure-count difference, not full conversions'}],'doeNetAudit':{'status':'Unresolved source-unit/conversion discrepancy, not established cause or definitive correction','printedTableTitle':'Direct and Indirect Whole-Store Climate Impacts - September2013 to July2014','rowHeading':'Propane Usage — Site(MMBtu); Source(MT CO2 Eq.)','impliedFactorsKgPerMMBtu':[13.18*1000/766,26.56*1000/1543],'unitChecks':'Saved screenshot confirms MMBtu, not therm or m3. Surrounding paragraph describes whole-store propane/electricity bills; no refrigeration-only allocation factor documented. Source-energy chart is separate from site-usage table.','sourceReportedDifferenceTCO2e':176,'sourceComponentDifferenceTCO2e':(975+13.18+191)-(976+26.56+.1),'diagnosticRecalculations':audit,'screenshots':['walmart-sources/walmart-hannaford-table.png','walmart-sources/walmart-emissions-page31.png']},'unknowns':unknown,'sources':sources}
(p/'walmart-deep.json').write_text(json.dumps(d,indent=2)+'\n')
print('walmart-deep.json written;',len(e),'evidence records; audit',audit)
